### ISSUE TITLE
Integrating example dataset with pixel, cell, and post clustering 

### ISSUE THREAD

**Issue by alex-l-kong** [angelolab/ark-analysis#692]
*This is for internal use only; if you'd like to open an issue or request a new feature, please open a bug or enhancement issue*

**Section 1: Design details**

**Relevant background**

After the example dataset is finalized for the segmentation notebook, it needs to integrate seamlessly into pixel and cell clustering.

**Design overview**

This project will require us to refactor the directory structure of `example_dataset`. We should have no less than all the required input files for each script, and no extraneous files either.

**Design list/flowchart**

Our sample dataset folder should look like:

```sh
data/
└── example_dataset/
    ├── input_data/
    │   ├── fov0/
    │   │   ├── ...
    │   ├── ...
    ├── segmentation/
    │   ├── deepcell_input/
    │   ├── deepcell_output/
    │   │   ├── fov0_feature_0.tif
    │   │   ├── ...
    │   ├── deepcell_visualization/
    │   ├── pixel_mat_data/
    │   │   ├── fov0.feather
    │   │   ├── ...
    │   ├── {pixel_cluster_prefix}_pixel_output_dir/
    │   │   ├── cell_clustering_params.json
    │   │   ├── pixel_channel_avg_som_cluster.csv
    │   │   ├── pixel_channel_avg_meta_cluster.csv
    │   └── cell_table/
    │   │   ├── example_cell_table_size_normalized.csv
    │   │   ├── example_cell_table_arcsinh_transformed.csv
```

`cell_clustering_params.json` should be set up as follows:

```
{
    'fovs': ['fov0', 'fov1', ...],
    'channels': [//list of channels used],
    'segmentation_dir': 'path_to_deepcell_output',
    'seg_suffix': '_feature_0.tif',
    'pixel_data_dir': 'path_to_pixel_mat_data',
    'pc_chan_avg_som_cluster_name': 'path_to_pixel_channel_avg_som_cluster.csv',
    'pc_chan_avg_meta_cluster_name': 'path_to_pixel_channel_avg_meta_cluster.csv'
}
```

A few notes:

- `pixel_mat_data` normally gets placed inside the `pixel_output_dir` folder. We need to separate this out in the example dataset so pixel clustering doesn't skip training/assignment/consensus clustering and cell clustering can use example pixel clustered data. `cell_clustering_params.json` needs to be set with the appropriate paths.
- The data in `pixel_mat_data` must include `pixel_som_cluster`, `pixel_meta_cluster`, and `pixel_meta_cluster_rename` columns.
- The cell tables need to include `pixel_meta_cluster` columns in order for notebook 4 to be demoed at any time. Notebook 4 should reference these example cell tables, and not the ones created by notebook 1 (because the cell tables generated by the latter don't contain a `pixel_meta_cluster` column).
    - The data other than the `pixel_meta_cluster` column will otherwise be exactly identical.

For Hugging Face, we will need to create the following datasets:

```sh
segmentation/
├── fov0_feature_0.tif
├── ...
└── fov10_feature_0.tif
```

```sh
cell_tables/
├── cell_table_arcsinh_transformed.csv
└── cell_table_size_normalized.csv
```

```sh
{pixel_cluster_prefix}_pixel_output_dir/
├── pixel_channel_avg_meta_cluster.csv
├── pixel_channel_avg_som_cluster.csv
└── cell_clustering_params.json
```

```sh
pixel_mat_data/
├── fov0.feather
├── ...
└── fov10.feather
```

In addition the loading script needs to be adjusted (by adding builder configs) for each of these. In addition the loading function in Ark, will need to be adjusted to account for them as well.

**Required inputs**

This is detailed in the above section.

**Output files**

The outputs each notebook produces will be the same as running the example dataset through the entire process as it stands.

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one. 

Timeline Give a rough estimate for how long you think the project will take. In general, it's better to be too conservative rather than too optimistic.

**Multiple weeks.** For large projects, make sure to agree on a plan that isn't just a single monster PR at the end.

Create 1 PR for each notebook:

1. Notebook 2: Cluster Pixels -- #736
   1. [x] Update the dataset on HuggingFace
   2. [x] Edit the notebook paths
   3. [x] Edit the test functions
   4. [x] Edit the notebook tests
2. Notebook 3: Cluster Cells -- #760 
   1. [x] Update the dataset on HuggingFace
   2. [x] Edit the notebook paths
   3. [x] Edit the test functions
   4. [x] Edit the notebook tests
3. Notebook 4: Post Clustering -- #763 
   1. [x] Update the dataset on HuggingFace
   2. [x] Edit the notebook paths
   3. [x] Edit the test functions
   4. [x] Edit the notebook tests

Estimated date when a fully implemented version will be ready for review: 9/30

Estimated date when the finalized project will be merged in: 10/7

**Comment by srivarra** [comment]
After downloading and moving the dataset to the proper `data` directory we would have:


**Extracted Image Data:**

```sh
data/
└── example_dataset/
    └── segmentation/
        └── deepcell_output/
            ├── fov0_feature_0.tif
            ├── ...
            └── fov10_feature_0.tif
```

**Cell Tables:**

```sh
data/
└── example_dataset/
    └── segmentation/
        └── cell_tables/
            ├── cell_table_arcsinh_transformed.csv
            └── cell_table_size_normalized.csv
```

And then for the Hugging Face Dataset, that would require a few more zip files, consisting of the following:

```sh
segmentation/
├── fov0_feature_0.tif
├── ...
└── fov10_feature_0.tif
```

```sh
cell_tables/
├── cell_table_arcsinh_transformed.csv
└── cell_table_size_normalized.csv
```

```sh
{pixel_cluster_prefix}_pixel_output_dir/
├── pixel_mat_data/
│   ├── fov0.feather
│   ├── ...
│   └── fov10.feather
├── {pixel_cluster_prefix}_pixel_channel_avg_meta_cluster.csv
├── {pixel_cluster_prefix}_pixel_channel_avg_som_cluster.csv
└── {pixel_cluster_prefix}_cell_clustering_params.json
```


For the name of the `pixel_cluster_prefix`, should we name it after the project it's from instead? Also if the `pixel_cluster_prefix` is already there for the `pixel_output_dir` do we need it for the `som`, `meta`, and `cell_clustering_params` files?

**Comment by alex-l-kong** [comment]
@srivarra we can, however we need to ensure this makes it into the pixel and cell clustering notebooks so it runs seamlessly. 
We should probably update the `pixel_cluster_prefix` and `cell_cluster_prefix` vars, as well as the file names we load in prior to cell clustering.

Currently, we do need `pixel_cluster_prefix` in the `som`, `meta`, and `cell_clustering_params` file names. I agree it's a bit unnecessary since we're already putting them in a folder prefixed with `pixel_cluster_prefix`. @ngreenwald let us know what you think.

**Comment by ngreenwald** [comment]
The `segmentation` and `cell_tables` folders should be standardized, like you mentioned above, so that they're only present in one spot. Currently, the `segmentation` example dataset only has the inputs, not the `deepcell_output` folder. We want the `deepcell_output` folder to be in the right spot. So if it's annoying to have a separate huggingface dataset with deepcell_output that needs to be copied into the previously created `segmentation` folder on the user's computer, I think it's fine to just have a single example dataset that contains all of the necessary files that we add to as we create the necessary data for the whole pipeline

You can pick a pixel-cluster prefix that makes sense, and then use that one and update it in the notebooks. 

@cliu72 wanted the individual files named with the prefix, I think in case the user re-runs code to avoid overwriting. I don't remember if there was a reorg since then or not, you should check with her

**Comment by cliu72** [comment]
I don't think we need the prefix for all the files - just the prefix on the directory name is fine. I think if a user re-runs code, they can just specify another prefix, which would make a new output directory.

**Comment by ngreenwald** [comment]
Cool, thanks Candace. 
Will you guys tag me in this once you've edited the design doc with all the changes? It would be helpful to have a single overview of the directory structure for all the files.

**Comment by alex-l-kong** [comment]
@srivarra can you check the updated structure to see if that works for HuggingFace?

**Comment by srivarra** [comment]
@alex-l-kong yeah that will work.

**Comment by alex-l-kong** [comment]
@srivarra double checking the process, looks like there's no workaround for needing `pixel_mat_data` with the SOM and consensus labels added for cell clustering. The only way we can ensure pixel clustering doesn't skip the training steps 
_and_ cell clustering runs with the pixel labeled data is to put this in a separate folder.

This can still be easily integrated, as all that's needed is for `cell_clustering_params.json` to point to the correct paths. Namely, the ones assigned to the `pixel_mat_data`, `pc_chan_avg_som_cluster_name`, and `pc_chan_avg_meta_cluster_name` keys.

**Comment by ngreenwald** [comment]
So will this reorganization mean that we lose the ability to skip reprocessing the data if it doesn't need to be?

**Comment by alex-l-kong** [comment]
@ngreenwald no, if there are already proper labels assigned to the data, reprocessing will be skipped. 

This reorg just ensures that when running the example dataset through pixel and cell clustering, no steps fail or get skipped.
